import os

DEFAULT_GOOGLE_LANGUAGE = os.getenv("ARCADE_GOOGLE_LANGUAGE", "en")

DEFAULT_YOUTUBE_SEARCH_LANGUAGE = os.getenv(
    "ARCADE_YOUTUBE_SEARCH_LANGUAGE", DEFAULT_GOOGLE_LANGUAGE
)
DEFAULT_YOUTUBE_SEARCH_COUNTRY = os.getenv("ARCADE_YOUTUBE_SEARCH_COUNTRY", None)
